### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by LincMitch** [alampros/babel-plugin-react-sketchapp-svg#1]
Thank's for the work.

Does this mean:
1.  I don't have to prefix my SVG tags with `Svg.`
2. I can import regular SVGs

Is that the reason you did this?

Do I need to install or learn babel to use your code in my project?

Thx again.
Link

**Comment by thierryc** [comment]
For me, you can import regular SVGs ! 
That is the goal of this babel plug-in. Like the "babel-plugin-inline-react-svg" works for react-dom. 

Babel config

```js

"babel": {
    "plugins": [
      "transform-class-properties",
      [
        "babel-plugin-react-sketchapp-svg",
        {
          "defaultHeight": 16,
          "defaultWidth": 16
        }
      ]
    ],
    "presets": [
      "env",
      "react",
      "stage-0"
    ]
  }

```

import in js

```

import React from 'react'
import PropTypes from 'prop-types'
import { Svg, makeSymbol } from 'react-sketchapp'

import IconAccessAlarm from '../svg-tmp/access_alarm.svg'
import IconAccessAlarms from '../svg-tmp/access_alarms.svg'

...

```

svg exemple 

```

<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
  <rect height="48" width="48" y="0" x="0" fill="none"/>
  <path d="M44 11.44l-9.19-7.71-2.57 3.06 9.19 7.71L44 11.44zM15.76 6.78l-2.57-3.06L4 11.43l2.57 3.06 9.19-7.71zM25 16h-3v12l9.49 5.71L33 31.24l-8-4.74V16zm-1.01-8C14.04 8 6 16.06 6 26s8.04 18 17.99 18S42 35.94 42 26 33.94 8 23.99 8zM24 40c-7.73 0-14-6.27-14-14s6.27-14 14-14 14 6.27 14 14-6.26 14-14 14z"/>
</svg>

```

From https://github.com/alampros/react-sketchapp-svg-render-test#readme

**Comment by alampros** [comment]
Yes, as @thierryc mentioned, your code needs to be processed by babel in order to use this.

The important part is that you can then use your SVG files like any other `react-sketchapp`-compatible component (notice the PascalCase `IconAccessAlarm` in the code above?).
